### ISSUE TITLE
Will not build on OSX 10.15.7 / Node 15

### ISSUE THREAD

**Issue by mtwomey** [mhsjlw/node-leveldb-mcpe#12]
Error logs:

```
[ 90%] Building CXX object CMakeFiles/node_leveldb_mcpe_native.dir/src/entrypoint.cpp.o
In file included from /tmp/t/node-leveldb-mcpe/src/entrypoint.cpp:2:
/private/tmp/t/node-leveldb-mcpe/node_modules/nan/nan.h:52:3: error: This version of node/NAN/v8 requires a C++11 compiler
# error This version of node/NAN/v8 requires a C++11 compiler
  ^
In file included from /tmp/t/node-leveldb-mcpe/src/entrypoint.cpp:2:
In file included from /private/tmp/t/node-leveldb-mcpe/node_modules/nan/nan.h:56:
In file included from /Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/node.h:63:
In file included from /Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/v8.h:28:
/Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/cppgc/common.h:14:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class EmbedderStackState {
     ^
In file included from /tmp/t/node-leveldb-mcpe/src/entrypoint.cpp:2:
In file included from /private/tmp/t/node-leveldb-mcpe/node_modules/nan/nan.h:56:
In file included from /Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/node.h:63:
In file included from /Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/v8.h:29:
/Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/v8-internal.h:51:1: error: unknown type name 'constexpr'
constexpr intptr_t kIntptrAllBitsSet = intptr_t{-1};
^
/Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/v8-internal.h:51:19: error: expected ';' after top level declarator
constexpr intptr_t kIntptrAllBitsSet = intptr_t{-1};
                  ^
                  ;
/Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/v8-internal.h:52:1: error: unknown type name 'constexpr'
constexpr uintptr_t kUintptrAllBitsSet =
^
/Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/v8-internal.h:52:20: error: expected ';' after top level declarator
constexpr uintptr_t kUintptrAllBitsSet =
                   ^
                   ;
/Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/v8-internal.h:60:10: error: unknown type name 'constexpr'
  static constexpr intptr_t kSmiMinValue =
         ^
/Users/mtwomey/.cmake-js/node-x64/v15.5.0/include/node/v8-internal.h:60:28: error: expected ';' at end of declaration list
  static constexpr intptr_t kSmiMinValue =
```
